server:
  port: 8080

spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
    banner-mode: off
  datasource:
    driver-class-name: ${sky.datasource.driver-class-name}
    url: jdbc:mysql://${sky.datasource.host}:${sky.datasource.port}/${sky.datasource.database}?&useSSL=false
    #serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: ${sky.datasource.username}
    password: ${sky.datasource.password}
  data:
    redis:
      host: ${sky.redis.host}
      port: ${sky.redis.port}
      password: ${sky.redis.password}
      lettuce:
        pool:
          max-active: 8 # 最大连接
          max-idle: 8 # 最大空闲连接
          min-idle: 0 # 最小空闲连接
          max-wait: 100 # 连接等待时间
      database: 1
#mybatis:
#  #mapper配置文件
#  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package: com.sky.entity
#  configuration:
#    #开启驼峰命名
#    map-underscore-to-camel-case: true

mybatis-plus:
  global-config:
    banner: false
    db-config:
      id-type: auto
  type-aliases-package: com.sky.entity
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    com:
      sky:
        mapper: debug
        service: info
        controller: info

sky:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: itcast
    # 设置jwt过期时间
    admin-ttl: 7200000
    # 设置前端传递过来的令牌名称
    admin-token-name: token

    user-secret-key: wechat
    user-ttl: 72000000
    user-token-name: authentication
  alioss:
    endpoint: ${sky.alioss.endpoint}
    access-key-id: ${sky.alioss.accessKeyId}
    access-key-secret: ${sky.alioss.accessKeySecrets}
    bucket-name: ${sky.alioss.bucketName}
  wechat:
    appid: ${sky.wechat.appid}
    secret: ${sky.wechat.secret}
#pagehelper:
#  reasonable: true
#  page-size-zero: true
#  params: count=countSql
#  helper-dialect: mysql

