sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123258
  alioss:
    endpoint: oss-cn-hangzhou.aliyuncs.com
    accessKeyId: LTAI5tLNf5xY5xQ11KbwBzus
    accessKeySecret: eCKPcJdIGTc2tJNHKJE0mAqr1fugMb
    bucketName: jigsawx
  redis:
    host: 192.168.13.140
    port: 6379
    password: 123258
  wechat:
    appid: wxda5dac773d804bb4
    secret: 6db39358211556df2b3fc9e0aeaffe0a